config-version: 2

name: 'fivetran_log'
version: '0.0.1'

require-dbt-version: '>=0.17.0'

models:
    fivetran_log:
        materialized: table # ephemeral after testing


# delete profile after testing
profile: integration_test