config-version: 2

name: 'fivetran_log'
version: '0.0.1'

require-dbt-version: '>=0.17.0'

models:
    fivetran_log:
        materialized: table # ephemeral after testing

vars:
    fivetran_log:
        unioning_multiple_destinations: false # disables macro for combining multiple destinations' Log Connectors

        account: "{{ source('fivetran_log', 'account') }}" 
        account_membership: "{{ source('fivetran_log', 'account_membership') }}"
        active_volume: "{{ source('fivetran_log', 'active_volume') }}"
        connector: "{{ source('fivetran_log', 'connector') }}"  
        credits_used: "{{ source('fivetran_log', 'credits_used') }}"
        destination: "{{ source('fivetran_log', 'destination') }}"
        destination_membership: "{{ source('fivetran_log', 'destination_membership') }}" 
        log: "{{ source('fivetran_log', 'log') }}" 
        transformation: "{{ source('fivetran_log', 'transformation') }}"
        trigger_table: "{{ source('fivetran_log', 'trigger_table') }}"
        user: "{{ source('fivetran_log', 'user') }}"


# delete profile after testing
profile: integration_test
