config-version: 2

name: 'fivetran_log'
version: '0.0.1'

require-dbt-version: '>=0.17.0'

models:
    fivetran_log:
        materialized: table # ephemeral after testing

vars:
    # Input the sources declared in src_fivetran_log.yml. They *must* match.
    source_destinations: [ 'fivetran_log_digital_arbor_400'] 
    # The above destinations that have transformations
    source_destinations_with_transformations: ['fivetran_log_dbt_package_testing'] 

# delete profile after testing
profile: dev_bigquery_dbt_testing